//ESTE ARCHIVO CONTIENE LOS ICONOS DEL CARRITO Y DE FAVORITOS
// BASICAMENTE ES UNA EVOLUCION DEL ARCHIVO CartWidget.jsx

//VAMOS A PROBRAR EL NO USO DE ESTE ARHIVO Y USAR SOLO CartWidget.jsx

//SI QUEDA BIEN CON EL OTRO, BORRAMOS ESTE, O BIEN NO LO USAMOS.
